### ISSUE TITLE
Numpy Error

### ISSUE THREAD

**Issue by arpit2412** [a5507203/Instance-dependent-Label-noise-Learning-under-a-Structural-Causal-Model#1]
I am trying to reimplement the code it's giving me a lot of errors like:

File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN

Would it be possible to provide requirements.txt file containing all  the libraries used with version

**Comment by a5507203** [comment]
requirements.txt is created
